name: alu_academic_assistant
description: A personal academic assistant app for ALU students.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
# flutter:
#   uses-material-design: true
#   fonts:
#     - family: Poppins
#       fonts:
#         - asset: assets/fonts/Poppins-Regular.ttf
#         - asset: assets/fonts/Poppins-Medium.ttf
#           weight: 500
#         - asset: assets/fonts/Poppins-SemiBold.ttf
#           weight: 600
#         - asset: assets/fonts/Poppins-Bold.ttf
#           weight: 700
